### PR TITLE
added initial guess of typescript typings

### PR DESCRIPTION
**Pull request by harjuto**

### CODE REVIEW

**Comment by harjuto** [comment]
There might be some clarification needed with optional fields. This setup seemed to be quite ok, thought its strange that you have to pass className etc.

**Comment by fraserxu** [comment]
Looks good! Do you need to add `"types": "dist/index.d.ts",` to `package.json` as well so TypeScript knows to where to find them?

**Comment by harjuto** [comment]
If its at the root of the project, next to index.js, you do not need to declare it in package.json. But it seems to be a good convention to put it there anyway :) Good that you pointed it out!

**Comment by fraserxu** [comment]
Ah, I didn't know that if it's next index.js.

**Comment by fraserxu** [comment]
FYI I started to rewrite this library in TypeScript but has continue too far yet lol.  https://github.com/fraserxu/react-dropdown/tree/typescript

**Pull request merged**
