### PR TITLE
Dropdown control div -> button

### PR DESCRIPTION
**Pull request by paulmelnikow**
Thanks for your work on this great component! Nice to have a simple option here.

I'm migrating an app from bootstrap to react.

This change use a more specific element name for the dropdown control, which should better harmonize the styling with existing button styles on a page.

Change in style.css preserves the appearance.

### CODE REVIEW

**Comment by fraserxu** [comment]
@paulmelnikow Thanks for the PR, I saw you are committing code to the `index.js` file, but this file is generated from the `src` file which I'm using `jsx`. Could you make the change there? Thanks. :D

**Comment by paulmelnikow** [comment]
Fixed, sorry about that! And sorry it took so long!

**Comment by paulmelnikow** [comment]
Rebased latest master.

**Comment by paulmelnikow** [comment]
Hey @fraserxu I just noticed this was still open. I rebased it off latest master. Would you mind taking a quick look?

**Pull request closed without merging**
