### PR TITLE
Fix placeholder being shown instead of selected value on rerender

### PR DESCRIPTION
**Pull request by AlexBeauchemin**
Issue: https://github.com/fraserxu/react-dropdown/issues/43

### CODE REVIEW

**Comment by AlexBeauchemin** [comment]
You're right, made this in a hurry. Added changes to source files

**Comment by fraserxu** [comment]
Sorry @AlexBeauchemin @episodeyang for the late response. I'm creating a new release now.

**Comment by fraserxu** [comment]
Published to react-dropdown@1.0.4 Please let me know if there's still issues, thanks @AlexBeauchemin @episodeyang

**Comment by episodeyang** [comment]
Thanks @fraserxu !

**Pull request merged**
