### PR TITLE
Allow customizing classes with a baseClassName prop

### PR DESCRIPTION
**Pull request by ahstro**
Allow adding classes to the root div with the `className` props, so that
```jsx
<Dropdown className="foobar" />
```
renders
```html
<div class="Dropdown foobar">
```

### CODE REVIEW

**Comment by ahstro** [comment]
Another idea might be to just have a `baseClassName` (or just `className`) prop and set every className after it, so that
```jsx
<Dropdown baseClassName="my-dropdown" />
```
would generate 
```html
<div class="my-dropdown-root">
  <div class="my-dropdown-control"></div>
  <div class="my-dropdown-menu">
    <div class="my-dropdown-option">
    </div>
  </div>
</div>
```

**Comment by fraserxu** [comment]
@ahstro Sounds like a brilliant idea, this would make it easy for people to customise things!

**Comment by ahstro** [comment]
Okay, that should do it. I went ahead and added the baseClassName to some classNames that didn't have the `Dropdown-`-prefix prior to this, because it seemed to make more sense to just give specific classes to all elements rendered by the component. No offense taken if you decide against it :)

**Comment by fraserxu** [comment]
Great stuff! @ahstro  I welcome any progressively enhanced step to make the api more flexible and still easy to use!

**Pull request merged**
